version: '3.8'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OANDA_API_KEY=${OANDA_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - PORT=8000
